#!/usr/bin/env bash
# Configures a server with HAProxy

apt update -y && apt upgrade -y
apt install haproxy=1.6.\* -y

echo "ENABLED=1" >>/etc/default/haproxy

haproxy_cfg="\nbackend web-backend\n\tbalance roundrobin\n\tserver 29572-web-01 44.197.198.112:80 check\n\tserver 29572-web-02 3.239.43.67:80 check\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"

echo -e "$haproxy_cfg" >>/etc/haproxy/haproxy.cfg

service haproxy restart
