#!/usr/bin/env bash
# fixing an nginx installation that is not listening on port 80
sed -i '/sites-enabled/a\        include /etc/nginx/sites-available/*;' /etc/nginx/nginx.conf
sudo service nginx restart
