#!/usr/bin/env bash
# Bash script that creates file and

echo $$ >/var/run/myscript.pid

trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm -f /var/run/holbertonscript.pid; exit" SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
