#!/usr/bin/env bash
# Displays the phrase "Best School" 10 times
# but for the 9th iteration it also adds hi
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ] 
    then
        echo "Hi"
    fi
    ((i++))
done
